spring:
  application:
    name: hulk-task
eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl.defaultZone}
logging:
  config: /opt/logconfig/hulk-task-logback.xml