server:
  port: 8000
#  context-path: /test
spring:
  aop:
    proxyTargetClass: true
  application:
    name: hulkServiceB
eureka:
  instance:
      preferIpAddress: true
      client:
          serviceUrl:
            defaultZone: ${eureka.serviceUrl.defaultZone}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000