spring:
  aop:
    proxyTargetClass: true
  application:
    name: hulkServiceA
eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl.defaultZone}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

logging:
  config: /apps/config/logconfig/hulk-logback.xml