spring:
  application:
    name: hulk-job
eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl.defaultZone}
logging:
  config: /opt/logconfig/hulk-logback.xml